# Generated by Django 2.1.4 on 2018-12-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
